force-app/main/default/objects/Investor__c/Investor__c.object-meta.xml
<CustomObject>
    <description>Purpose: Represents people investing in properties.</description>
    <label>Investor</label>
    <nameField>
        <label>Investor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Investment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Investment_Amount__c</fullName>
    <formula>Lots_Purchased__c  *  Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Investment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Investor__c.field-meta.xml
<CustomField>
    <fullName>Investor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Who made this investment</description>
    <label>Investor</label>
    <referenceTo>Investor__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortfolioCalculator.cls
public class PortfolioCalculator {
    
    // Method to calculate portfolio value for an investor
    public static Decimal calculatePortfolio(Id investorId) {
        Decimal totalValue = 0;
        List<Transaction__c> txns = [SELECT Investment_Amount__c FROM Transaction__c WHERE Investor__c = :investorId];
        for(Transaction__c t : txns){
            totalValue += t.Investment_Amount__c;
        }
        return totalValue;
    }

}